### ISSUE TITLE
Handling empty msgstr case

### ISSUE THREAD

**Issue by us3r64** [leonelquinteros/gotext#9]
If msgstr is empty ```msgstr ""``` shouldn't the original string, untranslated version, be returned?

After some tests this looks for me the right checks to handle the empty case

```
func (t *translation) get() string {
    // Look for translation index 0
    if _, ok := t.trs[0]; ok {
        // handle empty msgstr
        if len(t.trs[0]) == 0 {
            return t.id
        }
        return t.trs[0]
    }

    // Return unstranlated id by default
    return t.id
}

func (t *translation) getN(n int) string {
    // Look for translation index
    if _, ok := t.trs[n]; ok {
        // handle empty msgstr
        if len(t.trs[n]) == 0 {
            if len(t.pluralID) == 0 {
                return t.id
            }
            return t.pluralID
        }
        return t.trs[n]
    }

    // Return unstranlated plural by default
    return t.pluralID
}

```

**Comment by us3r64** [comment]
That will actually break `Multi line strings and headers`. 
Can trim the original string, but looks ugly at this point:

```
// Check for multiline from previously set msgid
if po.trBuffer.id != "" {
    // Append to last translation found
    uq, _ := strconv.Unquote(l)
    po.trBuffer.trs[len(po.trBuffer.trs)-1] = strings.TrimPrefix(po.trBuffer.trs[len(po.trBuffer.trs)-1], po.trBuffer.id)
    po.trBuffer.trs[len(po.trBuffer.trs)-1] += uq
}
```

**Comment by leonelquinteros** [comment]
You're right, as defined in https://www.gnu.org/software/gettext/manual/html_node/Untranslated-Entries.html empty translation strings should be handled as "untranslated". 

I've pushed a fix for this and will do a small release for it. 

Thanks for reporting!

**Comment by us3r64** [comment]
Hi,

The issue is not fixed 100%. 

For `GetD` you do `GetND` with plural set to `1` but `pluralID` doesn't get set.

So for empty msgstr you still get `""`, make sense?
